baseURL = "https://liamwh.com"
languageCode = "en-us"
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  # Header
  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Education"
  URL = "#education"
  weight = 3

  [[menu.header]]
  name = "Experience"
  URL = "#experience"
  weight = 4

  [[menu.header]]
  name = "Projects"
  URL = "#portfolio"
  weight = 5

  [[menu.header]]
  name = "Awards"
  URL = "#award"
  weight = 6

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 7

  # Footer
  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Education"
  URL = "#education"
  weight = 3

  [[menu.footer]]
  name = "Experience"
  URL = "#experience"
  weight = 4

  [[menu.footer]]
  name = "Projects"
  URL = "#portfolio"
  weight = 5

  [[menu.footer]]
  name = "Awards"
  URL = "#award"
  weight = 6

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 7


[params]

  sections = ["showcase", "about", "education", "experience", "portfolio", "award", "contact"]

  googleTagManagerID = "GTM-K2F9DP5"

  [params.logo]
    text1 = "Liam."