baseURL = "https://liamwh.com"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  # Header
  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Education"
  URL = "#education"
  weight = 3

  [[menu.header]]
  name = "Experience"
  URL = "#experience"
  weight = 4

  [[menu.header]]
  name = "Awards"
  URL = "#award"
  weight = 5

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6

  # Footer
  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Education"
  URL = "#education"
  weight = 3

  [[menu.footer]]
  name = "Experience"
  URL = "#experience"
  weight = 4

  [[menu.footer]]
  name = "Awards"
  URL = "#award"
  weight = 5

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 6


[params]

  #sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]
  sections = ["showcase", "about", "education", "experience", "award", "contact"]

  googleTagManagerID = "GTM-K2F9DP5" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Liam."
    #text2 = "WH"

  #[params.footer]
      #copyright = "© LiamWH. All rights reserved."
      # [params.footer.radity_logo]
      #   x = "img/general/design-and-code-radity.png"
      #   _2x = "img/general/design-and-code-radity@2x.png"
      #   alt = "Design & Code - Radity"